version: "3.4"

services:
  webapp:
    build:
      context: .
      args:
        - dotnet_configuration=${DOTNET_CONFIGURATION}
    ports:
      - 8080:80
      - 8443:443
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      # - ASPNETCORE_URLS=https://+:443;http://+:80
      # - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    
    # volumes:
    #  - ~/.aspnet/https:/https:ro

  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus:latest

    # user: "${UID}:${UID}" # TODO?
    user: root # XXX FIXME

    depends_on:
      - webapp
    ports:
      - 9090:9090
    volumes:
      # - ./containers:/ # TODO?
      - ./containers/etc/prometheus:/etc/prometheus # XXX?

      - ./data/prometheus:/prometheus
      # - data_prometheus:/prometheus # TODO?
    command:
      - "--config.file=/etc/prometheus/windows.config.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=200h"
      - "--web.enable-lifecycle"

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      # - ./containers:/ # TODO?
      - ./containers/etc/grafana:/etc/grafana
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=${GF_USERS_ALLOW_SIGN_UP}
      - GF_INSTALL_PLUGINS=${GF_INSTALL_PLUGINS}
